# Generated by Django 4.0.4 on 2022-05-13 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(default='new', max_length=250),
            preserve_default=False,
        ),
    ]
