# Generated by Django 4.0.4 on 2022-05-06 13:54

from django.db import migrations, models
import django.db.models.deletion
import task.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.BigIntegerField(default=task.models.get_id, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='task.basemodel')),
                ('title', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=250)),
                ('status', models.CharField(choices=[('new', 'new'), ('completed', 'completed')], max_length=100)),
                ('assignee', models.BigIntegerField()),
                ('fee', models.DecimalField(decimal_places=10, max_digits=15)),
            ],
            bases=('task.basemodel',),
        ),
    ]
