version: "3.9"

services:
  task_service:
    build: ./
    environment:
      OAUTH_CLIENT_ID: ${OAUTH_CLIENT_ID}  # take it from the "auth_service" UI 
      OAUTH_CLIENT_SECRET: ${OAUTH_CLIENT_SECRET}  # take it from the "auth_service" UI 

      # auth_service compose network settings
      OAUTH_URL: http://0.0.0.0:3000/oauth/authorize
      OAUTH_TOKEN_URL: http://oauth:3000/oauth/token
      OAUTH_ACCONT_INFO_URL: http://oauth:3000/accounts/current
      # 
      OAUTH_REDIRECT_URL: http://0.0.0.0:7777/auth_callback
      # for dev only purpose 
      OAUTHLIB_INSECURE_TRANSPORT: 1
      RABBITMQ_DSN: 'rabbitmq'
      LOG_LEVEl: DEBUG
    command: python manage.py runserver 0.0.0.0:7777
    networks:
      - rabbitmq_network
    volumes:
      - ./:/code
    ports:
      - "0.0.0.0:7777:7777"
    depends_on:
      - task_service_migration

  task_service_migration:
    build: ./
    command: bash -c "python manage.py migrate --noinput"
    networks:
      - rabbitmq_network
    environment:
      OAUTH_CLIENT_ID: ${OAUTH_CLIENT_ID}  # take it from the "auth_service" UI 
      OAUTH_CLIENT_SECRET: ${OAUTH_CLIENT_SECRET}  # take it from the "auth_service" UI 

      # auth_service compose network settings
      OAUTH_URL: http://0.0.0.0:3000/oauth/authorize  
      OAUTH_TOKEN_URL: http://oauth:3000/oauth/token
      OAUTH_ACCONT_INFO_URL: http://oauth:3000/accounts/current
      # 
      OAUTH_REDIRECT_URL: http://0.0.0.0:7777/auth_callback
      # for dev only purpose 
      OAUTHLIB_INSECURE_TRANSPORT: 1
      RABBITMQ_DSN: 'rabbitmq'
      
    volumes:
      - .:/code

  task_service_cud_event_manager:
    build: ./
    command: bash -c "python manage.py consume_cud_events"
    networks:
      - rabbitmq_network
    environment:
      OAUTH_CLIENT_ID: ${OAUTH_CLIENT_ID}  # take it from the "auth_service" UI 
      OAUTH_CLIENT_SECRET: ${OAUTH_CLIENT_SECRET}  # take it from the "auth_service" UI 

      # auth_service compose network settings
      OAUTH_URL: http://0.0.0.0:3000/oauth/authorize  
      OAUTH_TOKEN_URL: http://oauth:3000/oauth/token
      OAUTH_ACCONT_INFO_URL: http://oauth:3000/accounts/current
      # 
      OAUTH_REDIRECT_URL: http://0.0.0.0:7777/auth_callback
      # for dev only purpose 
      OAUTHLIB_INSECURE_TRANSPORT: 1
      RABBITMQ_DSN: 'rabbitmq'
    depends_on:
      - task_service
    volumes:
      - .:/code

networks:
  rabbitmq_network:
    external: true